from pytest_matchers.plugin import pytest_assertrepr_compare
from src.tests.conftest import pytest_configure
from src.tests.test_plugin import _set_verbosity

pytest_configure
pytest_assertrepr_compare
_set_verbosity
